// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VijayAnand.BlazorTemplates
{
    internal sealed partial class Vsix
    {
        public const string Id = "BlazorTemplates.316c4442-1dec-424e-9a59-e9c637daede6";
        public const string Name = "Blazor Desktop Templates";
        public const string Description = @"Project template for hosting the Blazor component in the Windows Forms and WPF desktop application.";
        public const string Language = "en-US";
        public const string Version = "3.4.0.0";
        public const string Author = "Vijay Anand E G";
        public const string Tags = "Blazor, Desktop, WindowsForms, WinForms, WPF, Windows, Template, BlazorWebView, Hybrid, Razor, Web, GA, .NET MAUI, Client, Modernization, .NET 7, .NET 8";
    }
}
